
const KEY='jurnal-learn-english-v1';
const today=new Date();
const iso=d=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const fmt=d=>new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const defaults={sessions:[],vocab:[],resources:[],speaking:[],listening:[],topics:[],mistakes:[],goals:[],reflections:[]};
let data=load();
let calendarCursor=new Date(today.getFullYear(),today.getMonth(),1);let selectedDate=iso(today);
function load(){try{const raw=localStorage.getItem(KEY);if(raw)return {...defaults,...JSON.parse(raw)};}catch(e){}return structuredClone(defaults)}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function totalMinutes(){return data.sessions.reduce((a,s)=>a+(Number(s.duration)||0),0)+data.speaking.reduce((a,s)=>a+(Number(s.duration)||0),0)+data.listening.reduce((a,s)=>a+(Number(s.duration)||0),0)}
function activeVocab(){return data.vocab.filter(v=>v.status==='Active'||v.status==='Mastered').length}
function uniqueStudyDays(){return new Set([...data.sessions.map(s=>s.date),...data.speaking.map(s=>s.date),...data.listening.map(s=>s.date)]).size}
function skillValue(skill){const arr=data.sessions.filter(s=>s.skill===skill).map(s=>Number(s.result)||0);if(!arr.length)return 0;return Math.round(arr.reduce((a,b)=>a+b,0)/arr.length)}
function daysActiveLast30(){const set=new Set();const start=new Date();start.setDate(start.getDate()-29);[...data.sessions,...data.speaking,...data.listening].forEach(x=>{const d=new Date(x.date);if(d>=start)set.add(x.date)});return Math.round(set.size/30*100)}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+id));document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===id));closeMobileDrawer();window.scrollTo({top:0,behavior:'smooth'});}
function say(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1900)}
function jump(id){showPage(id)}
document.querySelectorAll('[data-page]').forEach(a=>a.addEventListener('click',()=>showPage(a.dataset.page)));
document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.jump)));
const moreMenu=document.getElementById('moreMenu');
const mobileMore=document.getElementById('mobileMore');
const sidebarEl=document.getElementById('sidebar');
const drawerOverlay=document.getElementById('drawerOverlay');
function closeMobileDrawer(){sidebarEl.classList.remove('open');drawerOverlay.classList.remove('show');mobileMore?.classList.remove('active');moreMenu?.classList.remove('show')}
function toggleMobileDrawer(){if(window.innerWidth>720)return;const open=!sidebarEl.classList.contains('open');sidebarEl.classList.toggle('open',open);drawerOverlay.classList.toggle('show',open);mobileMore.classList.toggle('active',open)}
mobileMore.onclick=toggleMobileDrawer;document.getElementById('drawerClose').onclick=closeMobileDrawer;
drawerOverlay.onclick=closeMobileDrawer;
document.querySelectorAll('[data-more-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.morePage)));
window.addEventListener('resize',()=>{if(window.innerWidth>720)closeMobileDrawer()});
document.getElementById('notify').onclick=()=>say('You have '+dueCount()+' review items due.');
document.getElementById('quick').onclick=()=>openModal('session');document.getElementById('quickTop').onclick=()=>openModal('session');

const clearGroups={
  learning:{label:'Learning Log',key:'sessions'},
  vocab:{label:'Vocabulary',key:'vocab'},
  speaking:{label:'Speaking',key:'speaking'},
  listening:{label:'Listening',key:'listening'},
  knowledge:{label:'Knowledge & Topics',key:'topics'},
  mistakes:{label:'Mistake Bank',key:'mistakes'},
  resources:{label:'Resources',key:'resources'},
  goals:{label:'Goals & Roadmap',key:'goals'},
  reflections:{label:'Reflections',key:'reflections'},
  review:{label:'Review data',key:null}
};
function openClearData(){
  const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),body=document.getElementById('modalBody');
  title.textContent='Clear selected data';
  body.innerHTML=`<form class="form clear-data-form" id="fClearData">
    <div class="clear-note"><strong>Choose what to remove.</strong><span>This only deletes the categories you select. There is no Clear All option.</span></div>
    <div class="clear-checks">${Object.entries(clearGroups).map(([id,g])=>`<label class="clear-check"><input type="checkbox" name="clearKey" value="${id}"><span><b>${g.label}</b><small>${id==='review'?'Clear review-related saved data':'Delete saved '+g.label.toLowerCase()}</small></span></label>`).join('')}</div>
    <label class="clear-confirm"><input type="checkbox" name="confirm" required><span>I understand the selected data will be removed from this device.</span></label>
    <button class="danger" type="submit">Clear selected data</button>
  </form>`;
  modal.classList.add('show');
  const form=body.querySelector('#fClearData');
  form.onsubmit=e=>{
    e.preventDefault();
    const selected=[...form.querySelectorAll('input[name="clearKey"]:checked')].map(x=>x.value);
    if(!selected.length){say('Select at least one data type.');return}
    if(!form.confirm.checked){say('Confirm before clearing.');return}
    const has=x=>selected.includes(x);
    if(has('learning')) data.sessions=[];
    if(has('vocab')) data.vocab=[];
    if(has('speaking')){
      const topics=new Set(data.speaking.map(x=>x.topic));
      data.speaking=[];
      data.sessions=data.sessions.filter(s=>!(s.activity||'').startsWith('Speaking: ')||!topics.has((s.activity||'').slice(10)));
    }
    if(has('listening')){
      const titles=new Set(data.listening.map(x=>x.title));
      data.listening=[];
      data.sessions=data.sessions.filter(s=>!(s.activity||'').startsWith('Listening: ')||!titles.has((s.activity||'').slice(11)));
    }
    if(has('knowledge')) data.topics=[];
    if(has('mistakes')) data.mistakes=[];
    if(has('resources')) data.resources=[];
    if(has('goals')) data.goals=[];
    if(has('reflections')) data.reflections=[];
    if(has('review')) { data.vocab=[]; data.mistakes=[]; }
    modal.classList.remove('show');
    save();
    say(selected.length===1 ? clearGroups[selected[0]].label+' cleared.' : selected.length+' data categories cleared.');
  };
}
function openModal(type){const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),body=document.getElementById('modalBody');const forms={
 session:['Add learning session',`<form class="form" id="fSession"><div class="grid two"><div><label>Date</label><input name="date" type="date" value="${iso(today)}"></div><div><label>Duration (minutes)</label><input name="duration" type="number" min="1" value="20"></div></div><label>What did you learn / do?</label><input name="activity" required placeholder="e.g. Casual conversation practice"><div class="grid two"><div><label>Skill</label><select name="skill"><option>Speaking</option><option>Listening</option><option>Vocabulary</option><option>Grammar</option><option>Reading</option><option>Writing</option><option>Pronunciation</option></select></div><div><label>Source</label><select name="source"><option>ChatGPT</option><option>YouTube</option><option>Course</option><option>Book</option><option>Website</option><option>Practice</option><option>Other</option></select></div></div><label>Result / understanding %</label><input name="result" type="number" min="0" max="100" value="70"><label>Notes</label><textarea name="notes" placeholder="What was easy, hard, or new?"></textarea><button class="primary">Save session</button></form>`],
 vocab:['Add vocabulary',`<form class="form" id="fVocab"><label>Word / phrase</label><input name="word" required placeholder="e.g. figure out"><label>Meaning</label><input name="meaning" required placeholder="Simple meaning in Indonesian or English"><label>Example sentence</label><textarea name="example" required placeholder="Use it in a full sentence."></textarea><div class="grid two"><div><label>Source</label><input name="source" placeholder="ChatGPT / YouTube / URL title"></div><div><label>Status</label><select name="status"><option>New</option><option>Learning</option><option>Familiar</option><option>Active</option><option>Mastered</option></select></div></div><label>Next review</label><input name="review" type="date" value="${iso(new Date(Date.now()+86400000*2))}"><button class="primary">Save vocabulary</button></form>`],
 speaking:['Log speaking',`<form class="form" id="fSpeaking"><div class="grid two"><div><label>Date</label><input name="date" type="date" value="${iso(today)}"></div><div><label>Duration (minutes)</label><input name="duration" type="number" value="15"></div></div><label>Topic</label><input name="topic" required placeholder="e.g. Daily routine"><div class="grid two"><div><label>Fluency /10</label><input name="fluency" type="number" min="1" max="10" value="7"><label>Vocabulary /10</label><input name="vocab" type="number" min="1" max="10" value="7"><label>Grammar /10</label><input name="grammar" type="number" min="1" max="10" value="7"></div><div><label>Pronunciation /10</label><input name="pronunciation" type="number" min="1" max="10" value="6"><label>Confidence /10</label><input name="confidence" type="number" min="1" max="10" value="7"></div></div><button class="primary">Save speaking session</button></form>`],
 listening:['Log listening',`<form class="form" id="fListening"><div class="grid two"><div><label>Date</label><input name="date" type="date" value="${iso(today)}"></div><div><label>Duration (minutes)</label><input name="duration" type="number" value="20"></div></div><label>Audio / video title</label><input name="title" required placeholder="e.g. Casual English conversation"><div class="grid two"><div><label>Understanding %</label><input name="understanding" type="number" min="0" max="100" value="65"></div><div><label>Replays</label><input name="replays" type="number" min="0" value="2"></div></div><div class="grid two"><div><label>Shadowing rounds</label><input name="shadowing" type="number" min="0" value="1"></div><div><label>Source</label><input name="source" value="YouTube"></div></div><button class="primary">Save listening session</button></form>`],
 resource:['Add resource',`<form class="form" id="fResource"><label>Resource title</label><input name="title" required placeholder="e.g. Casual English Conversation #12"><label>Resource URL</label><input name="url" type="url" required placeholder="https://..."><div id="resourcePreview" class="resource-preview" style="display:none"></div><div class="grid two"><div><label>Type</label><select name="type"><option>YouTube</option><option>Website</option><option>Course</option><option>Book</option><option>ChatGPT</option><option>PDF</option><option>Other</option></select></div><div><label>Skill</label><select name="skill"><option>Listening</option><option>Speaking</option><option>Vocabulary</option><option>Grammar</option><option>Reading</option><option>Writing</option><option>Pronunciation</option></select></div></div><div class="grid two"><div><label>Status</label><select name="status"><option>Saved</option><option>In progress</option><option>Completed</option></select></div><div><label>Rating /5</label><input name="rating" type="number" min="0" max="5" step="0.1" value="4"></div></div><label>Notes</label><textarea name="notes" placeholder="Why is this useful?"></textarea><button class="primary">Save resource</button></form>`],
 mistake:['Add mistake',`<form class="form" id="fMistake"><label>Wrong sentence</label><textarea name="wrong" required placeholder="What did you say/write?"></textarea><label>Correct sentence</label><textarea name="right" required placeholder="What should it be?"></textarea><div class="grid two"><div><label>Category</label><select name="category"><option>Grammar</option><option>Vocabulary</option><option>Pronunciation</option><option>Word order</option><option>Other</option></select></div><div><label>Times repeated</label><input name="count" type="number" min="1" value="1"></div></div><button class="primary">Save mistake</button></form>`],
 topic:['Add topic',`<form class="form" id="fTopic"><label>Topic</label><input name="name" required placeholder="e.g. Small talk"><div class="grid two"><div><label>Category</label><select name="category"><option>Conversation</option><option>Grammar</option><option>Listening</option><option>Vocabulary</option><option>Pronunciation</option><option>Reading</option><option>Writing</option></select></div><div><label>Mastery %</label><input name="mastery" type="number" min="0" max="100" value="50"></div></div><label>Confidence %</label><input name="confidence" type="number" min="0" max="100" value="50"><button class="primary">Save topic</button></form>`],
 goal:['Add goal',`<form class="form" id="fGoal"><label>Goal</label><input name="title" required placeholder="e.g. 20 speaking sessions"><div class="grid two"><div><label>Target number</label><input name="target" type="number" min="1" value="20"></div><div><label>Unit</label><input name="unit" value="sessions"></div></div><label>Month</label><input name="month" value="October"><button class="primary">Save goal</button></form>`],
 reflection:['Add reflection',`<form class="form" id="fReflection"><label>What improved?</label><textarea name="improved" required></textarea><label>What still feels difficult?</label><textarea name="difficult" required></textarea><label>What should change next?</label><textarea name="next" required></textarea><button class="primary">Save reflection</button></form>`]
};
 const [t,b]=forms[type]||forms.session;title.textContent=t;body.innerHTML=b;modal.classList.add('show');
 const form=body.querySelector('form');
 if(type==='resource'){
   const urlInput=form.querySelector('[name="url"]');
   const preview=form.querySelector('#resourcePreview');
   const updatePreview=()=>{const info=resourceThumbInfo(urlInput.value.trim()); if(!info){preview.style.display='none';preview.innerHTML='';return;} preview.style.display='block'; preview.innerHTML=thumbMarkup(urlInput.value.trim(),info.kind==='youtube'?'YouTube':'Website');};
   urlInput.addEventListener('input',updatePreview); urlInput.addEventListener('change',updatePreview);
 }
 form.noValidate=true;
 form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);const o=Object.fromEntries(fd.entries());
  const required=[...form.querySelectorAll('[required]')];
  const missing=required.find(input=>!String(input.value||'').trim());
  if(missing){missing.focus();say('Please fill in '+(missing.previousElementSibling?.textContent||'this field')+'.');return}
  if(type==='session'){o.id=uid();o.duration=+o.duration;o.result=+o.result;data.sessions.unshift(o)}
  if(type==='vocab'){o.id=uid();data.vocab.unshift(o)}
  if(type==='speaking'){o.id=uid();['duration','fluency','vocab','grammar','pronunciation','confidence'].forEach(k=>o[k]=+o[k]);data.speaking.unshift(o);data.sessions.unshift({id:uid(),date:o.date,activity:'Speaking: '+o.topic,skill:'Speaking',source:'Practice',duration:o.duration,result:Math.round((o.fluency+o.vocab+o.grammar+o.pronunciation+o.confidence)*2),notes:'Speaking log'})}
  if(type==='listening'){o.id=uid();['duration','understanding','replays','shadowing'].forEach(k=>o[k]=+o[k]);data.listening.unshift(o);data.sessions.unshift({id:uid(),date:o.date,activity:'Listening: '+o.title,skill:'Listening',source:o.source||'Other',duration:o.duration,result:o.understanding,notes:'Listening log'})}
  if(type==='resource'){o.id=uid();o.rating=+o.rating;o.duration=0;data.resources.unshift(o)}
  if(type==='mistake'){o.id=uid();o.count=+o.count;o.date=iso(today);o.status='Recurring';data.mistakes.unshift(o)}
  if(type==='topic'){o.id=uid();o.mastery=+o.mastery;o.confidence=+o.confidence;o.items=0;data.topics.unshift(o)}
  if(type==='goal'){o.id=uid();o.target=+o.target;o.current=0;data.goals.unshift(o)}
  if(type==='reflection'){o.id=uid();o.date=iso(today);data.reflections.unshift(o)}
  modal.classList.remove('show');save();say('Saved and connected across your dashboard.');
 };
}
document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('show');document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')});
['addSession','addVocab','addSpeaking','addListening','addResource','addMistake','addTopic','addGoal','addReflection'].forEach(id=>{const el=document.getElementById(id);if(el)el.onclick=()=>openModal({addSession:'session',addVocab:'vocab',addSpeaking:'speaking',addListening:'listening',addResource:'resource',addMistake:'mistake',addTopic:'topic',addGoal:'goal',addReflection:'reflection'}[id])});
function dueCount(){return data.vocab.filter(v=>v.review&&v.review<=iso(today)&&v.status!=='Mastered').length+data.mistakes.filter(m=>m.status==='Recurring').length}
function renderAll(){renderDashboard();renderLearning();renderVocab();renderSpeaking();renderListening();renderTopics();renderMistakes();renderResources();renderGoals();renderReview();renderCalendar();renderAnalytics();renderReflections()}
function renderDashboard(){document.getElementById('dashDate').textContent=today.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});const mins=totalMinutes();document.getElementById('dashStats').innerHTML=[['Study time',Math.floor(mins/60)+'h '+mins%60+'m','All logged learning'],['Study days',uniqueStudyDays(),'Days with activity'],['Active vocab',activeVocab(),data.vocab.length+' tracked words'],['Due review',dueCount(),'Items needing attention']].map(x=>`<div class="card stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('');
 const last7=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=iso(d);const sessions=data.sessions.filter(s=>s.date===key),speaking=data.speaking.filter(s=>s.date===key),listening=data.listening.filter(s=>s.date===key);const m=sessions.reduce((a,s)=>a+(+s.duration||0),0)+speaking.reduce((a,s)=>a+(+s.duration||0),0)+listening.reduce((a,s)=>a+(+s.duration||0),0);last7.push({key,m})}const max=Math.max(60,...last7.map(x=>x.m));const W=640,H=250,L=22,R=18,T=22,B=44;const cw=(W-L-R)/6;const pts=last7.map((x,i)=>[L+i*cw,T+(H-T-B)-(x.m/max)*(H-T-B)]);const line=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const area=line+' L '+pts[pts.length-1][0].toFixed(1)+' '+(H-B)+' L '+pts[0][0].toFixed(1)+' '+(H-B)+' Z';const labels=last7.map((x,i)=>{const d=new Date(x.key);return `<text x="${pts[i][0]}" y="${H-15}" text-anchor="middle" class="chart-label">${d.toLocaleDateString('en-US',{weekday:'short'})}</text>`}).join('');const dots=last7.map((x,i)=>`<circle cx="${pts[i][0]}" cy="${pts[i][1]}" r="4.5" class="chart-dot"><title>${x.m} min</title></circle>`).join('');document.getElementById('activityBars').innerHTML=`<div class="chart-total"><strong>${last7.reduce((a,x)=>a+x.m,0)} min</strong><span>total in the last 7 days</span></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="Learning activity over the last 7 days"><defs><linearGradient id="activityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#c9f34d" stop-opacity=".48"/><stop offset="100%" stop-color="#c9f34d" stop-opacity="0"/></linearGradient></defs><line x1="${L}" y1="${T+(H-T-B)/2}" x2="${W-R}" y2="${T+(H-T-B)/2}" class="chart-grid"/><line x1="${L}" y1="${H-B}" x2="${W-R}" y2="${H-B}" class="chart-grid"/><path d="${area}" fill="url(#activityFill)"/><path d="${line}" class="chart-line"/>${dots}${labels}</svg>`;
 const skills=['Speaking','Listening','Vocabulary','Grammar','Pronunciation'];document.getElementById('skillBalance').innerHTML=skills.map(s=>`<div class="skill"><span>${s}</span><div class="track"><div class="fill" style="width:${skillValue(s)}%"></div></div><b>${skillValue(s)}%</b></div>`).join('');
 document.getElementById('recentLearning').innerHTML=data.sessions.slice(0,5).map(s=>`<div class="row"><div><strong>${esc(s.activity)}</strong><small>${esc(s.date)} · ${esc(s.source)} · ${s.duration} min</small></div><span class="status ${s.result>=75?'active':'warn'}">${s.result}%</span></div>`).join('')||'<div class="empty">No learning sessions yet.</div>';
 const weakest=skills.sort((a,b)=>skillValue(a)-skillValue(b))[0];document.getElementById('recommendation').innerHTML=`<strong>Focus on ${weakest}</strong><p>Your current lowest tracked skill is <b>${skillValue(weakest)}%</b>. A short ${weakest.toLowerCase()} session today will have the highest impact.</p><button class="primary" onclick="showPage('${weakest==='Speaking'?'speaking':weakest==='Listening'?'listening':weakest==='Vocabulary'?'vocab':'learning'}')">Start ${weakest}</button>`;
 const activeThisWeek=[...new Set([...data.sessions,...data.speaking,...data.listening].filter(x=>{const d=new Date(x.date),n=new Date();const diff=(n-d)/86400000;return diff>=0&&diff<7}).map(x=>x.date))].length;document.getElementById('weekProgressText').textContent=activeThisWeek+'/7 active days';renderMiniCalendar();}
function renderMiniCalendar(){const el=document.getElementById('miniCalendar');const days=['S','M','T','W','T','F','S'];el.innerHTML=days.map(d=>`<div class="calday head">${d}</div>`).join('');const first=new Date(today.getFullYear(),today.getMonth(),1).getDay();for(let i=0;i<first;i++)el.innerHTML+='<div></div>';const n=new Date(today.getFullYear(),today.getMonth()+1,0).getDate();const active=new Set([...data.sessions,...data.speaking,...data.listening].map(x=>x.date));for(let d=1;d<=n;d++){const k=iso(new Date(today.getFullYear(),today.getMonth(),d));el.innerHTML+=`<div class="calday ${active.has(k)?'done ':''}${k===iso(today)?'today':''}" onclick="selectedDate='${k}';showPage('calendar');renderCalendar()">${d}</div>`}}
function renderLearning(){const skill=document.getElementById('learningSkillFilter').value,src=document.getElementById('learningSourceFilter').value;let arr=data.sessions.filter(s=>(skill==='all'||s.skill===skill)&&(src==='all'||s.source===src));document.getElementById('learningTable').innerHTML=arr.map(s=>`<tr><td>${esc(s.date)}</td><td><strong>${esc(s.activity)}</strong><div class="muted">${esc(s.notes||'')}</div></td><td><span class="tag">${esc(s.skill)}</span></td><td>${esc(s.source)}</td><td>${s.duration}m</td><td>${s.result}%</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No sessions match these filters.</div></td></tr>'}
function renderVocab(){document.getElementById('vocabStats').innerHTML=[['Tracked words',data.vocab.length,'All saved words'],['Active',activeVocab(),'Used or mastered'],['Learning',data.vocab.filter(v=>v.status==='Learning').length,'Still building recall'],['Due',data.vocab.filter(v=>v.review&&v.review<=iso(today)&&v.status!=='Mastered').length,'Review today']].map(x=>`<div class="card stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('');const q=(document.getElementById('vocabSearch').value||'').toLowerCase(),st=document.getElementById('vocabStatusFilter').value;const arr=data.vocab.filter(v=>(!q||v.word.toLowerCase().includes(q)||v.meaning.toLowerCase().includes(q))&&(st==='all'||v.status===st));document.getElementById('vocabTable').innerHTML=arr.map(v=>`<tr><td><strong>${esc(v.word)}</strong></td><td>${esc(v.meaning)}</td><td>${esc(v.example)}</td><td>${esc(v.source||'')}</td><td><span class="status ${v.status==='Mastered'||v.status==='Active'?'active':''}">${v.status}</span></td><td>${v.review||'—'}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No vocabulary found.</div></td></tr>'}
function renderSpeaking(){const arr=data.speaking;const avg=k=>arr.length?Math.round(arr.reduce((a,s)=>a+s[k],0)/arr.length*10)/10:0;document.getElementById('speakingStats').innerHTML=[['Sessions',arr.length,'Logged speaking practice'],['Minutes',arr.reduce((a,s)=>a+s.duration,0),'Total speaking time'],['Fluency',avg('fluency')+'/10','Average'],['Confidence',avg('confidence')+'/10','Average']].map(x=>`<div class="card stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('');document.getElementById('speakingList').innerHTML=arr.map(s=>`<div class="row"><div><strong>${esc(s.topic)}</strong><small>${s.date} · ${s.duration} min · Fluency ${s.fluency}/10 · Vocab ${s.vocab}/10</small></div><span class="status ${s.confidence>=7?'active':'warn'}">${s.confidence}/10</span></div>`).join('')||'<div class="empty">No speaking sessions.</div>';const ks=[['Fluency',avg('fluency')*10],['Vocabulary',avg('vocab')*10],['Grammar',avg('grammar')*10],['Pronunciation',avg('pronunciation')*10],['Confidence',avg('confidence')*10]];document.getElementById('speakingSkills').innerHTML=ks.map(x=>`<div class="skill"><span>${x[0]}</span><div class="track"><div class="fill" style="width:${x[1]}%"></div></div><b>${x[1]}%</b></div>`).join('')}
function renderListening(){const arr=data.listening;const avg=arr.length?Math.round(arr.reduce((a,s)=>a+s.understanding,0)/arr.length):0;document.getElementById('listeningStats').innerHTML=[['Sessions',arr.length,'Logged listening'],['Minutes',arr.reduce((a,s)=>a+s.duration,0),'Listening time'],['Understanding',avg+'%','Average comprehension'],['Shadowing',arr.reduce((a,s)=>a+s.shadowing,0),'Rounds logged']].map(x=>`<div class="card stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('');document.getElementById('listeningList').innerHTML=arr.map(s=>`<div class="row"><div><strong>${esc(s.title)}</strong><small>${s.date} · ${s.duration} min · ${s.replays} replays · ${s.shadowing} shadowing</small></div><span class="status ${s.understanding>=70?'active':'warn'}">${s.understanding}%</span></div>`).join('')||'<div class="empty">No listening sessions.</div>';document.getElementById('listeningSpark').innerHTML=arr.slice().reverse().map(s=>`<i style="height:${Math.max(7,s.understanding)}%" title="${s.understanding}%"></i>`).join('')}
function renderTopics(){document.getElementById('topicCards').innerHTML=data.topics.map(t=>`<div class="card mini"><div style="display:flex;justify-content:space-between;gap:8px"><h3>${esc(t.name)}</h3><span class="tag">${esc(t.category)}</span></div><div class="progressrow"><span>Mastery</span><b><span>${t.mastery}</span><small>%</small></b></div><div class="track"><div class="fill" style="width:${t.mastery}%"></div></div><div class="progressrow"><span>Confidence</span><b><span>${t.confidence}</span><small>%</small></b></div><div class="track"><div class="fill" style="width:${t.confidence}%"></div></div><p style="margin-top:10px">${t.items||0} tracked learning items connected to this topic.</p></div>`).join('')}
function renderMistakes(){const arr=data.mistakes.slice().sort((a,b)=>b.count-a.count);document.getElementById('mistakeList').innerHTML=arr.map(m=>`<div class="mistake"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(m.category)}</b><span class="status ${m.status==='Recurring'?'red':'active'}">${m.count}× · ${m.status}</span></div><div style="margin-top:7px"><strong>❌ ${esc(m.wrong)}</strong></div><div style="margin-top:4px;color:#3f5148">✅ ${esc(m.right)}</div><div class="muted" style="margin-top:6px">First logged ${m.date}. Repeated mistakes are prioritized for review.</div></div>`).join('')||'<div class="empty">No mistakes logged.</div>'}
function resourceThumbInfo(url){
  if(!url) return null;
  try{
    const u=new URL(url);
    const host=u.hostname.replace(/^www\./,'').toLowerCase();
    let id='';
    if(host==='youtu.be') id=u.pathname.split('/').filter(Boolean)[0]||'';
    else if(host==='youtube.com'||host==='m.youtube.com') id=u.searchParams.get('v')||((u.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/)||[])[1]||'');
    if(id && /^[A-Za-z0-9_-]{11}$/.test(id)) return {kind:'youtube',id,src:'https://i.ytimg.com/vi/'+id+'/maxresdefault.jpg'};
    return {kind:'website',src:'https://image.thum.io/get/width/1200/crop/675/noanimate/'+encodeURIComponent(url)};
  }catch(e){return null}
}
function resourceThumb(url){const info=resourceThumbInfo(url);return info?info.src:''}
function thumbMarkup(url,type){
  const info=resourceThumbInfo(url); if(!info) return '';
  if(info.kind==='youtube') return `<div class="resource-thumb-wrap"><img class="resource-thumb" src="${esc(info.src)}" alt="YouTube thumbnail" loading="lazy" data-thumb-id="${esc(info.id)}" onerror="this.dataset.step=(+this.dataset.step||0)+1;this.src=this.dataset.step==='1'?'https://i.ytimg.com/vi/${esc(info.id)}/hqdefault.jpg':this.dataset.step==='2'?'https://i.ytimg.com/vi/${esc(info.id)}/mqdefault.jpg':this.dataset.step==='3'?'https://i.ytimg.com/vi/${esc(info.id)}/default.jpg':'';if(!this.src)this.closest('.resource-thumb-wrap').remove()"><span class="resource-type">${esc(type||'YouTube')}</span></div>`;
  return `<div class="resource-thumb-wrap"><img class="resource-thumb" src="${esc(info.src)}" alt="Website thumbnail" loading="lazy" onerror="this.closest('.resource-thumb-wrap').remove()"><span class="resource-type">${esc(type||'Website')}</span></div>`;
}
function renderResources(){document.getElementById('resourceCards').innerHTML=data.resources.map(r=>`<div class="card mini">${thumbMarkup(r.url,r.type)}<div class="resource-card-body"><div style="display:flex;justify-content:space-between;gap:7px"><span class="tag">${esc(r.type)}</span><span class="status">${r.rating||0}★</span></div><h3 style="margin-top:12px">${esc(r.title)}</h3><p>${esc(r.notes||'')}</p><div style="margin-top:10px" class="muted">${esc(r.skill)} · ${esc(r.status)}</div><div style="margin-top:11px"><a class="link" href="${esc(r.url)}" target="_blank" rel="noopener">Open resource ↗</a></div></div></div>`).join('')||'<div class="card section"><div class="empty">No resources saved yet.</div></div>'}
function goalProgress(g){if(g.title.toLowerCase().includes('vocabulary'))return Math.min(g.target,activeVocab());if(g.title.toLowerCase().includes('listening'))return Math.min(g.target,data.listening.filter(s=>s.date.startsWith('2026-10')).length);if(g.title.toLowerCase().includes('speaking'))return Math.min(g.target,data.speaking.filter(s=>s.date.startsWith('2026-10')).length);return g.current||0}
function renderGoals(){document.getElementById('roadmap').innerHTML=[['September · Foundation',0],['October · Real conversation',Math.min(100,Math.round((data.speaking.length+data.listening.length+activeVocab()/5)))],['November · Natural conversation',0],['December · Confident conversation',0]].map(x=>`<div class="goal"><div class="goaltop"><span>${x[0]}</span><b>${x[1]}%</b></div><div class="goalbar"><span style="width:${x[1]}%"></span></div></div>`).join('');document.getElementById('goalCards').innerHTML=data.goals.map(g=>{const cur=goalProgress(g),pct=Math.min(100,Math.round(cur/g.target*100));return `<div class="card mini"><h3>${esc(g.title)}</h3><div class="progressrow"><span>${cur}/${g.target} ${esc(g.unit)}</span><b>${pct}%</b></div><div class="track"><div class="fill" style="width:${pct}%"></div></div><p style="margin-top:9px">${esc(g.month)} target · connected to live learning data.</p></div>`}).join('')}
function renderReview(){const dueV=data.vocab.filter(v=>v.review&&v.review<=iso(today)&&v.status!=='Mastered');const recurring=data.mistakes.filter(m=>m.status==='Recurring');document.getElementById('reviewStats').innerHTML=[['Due today',dueV.length+recurring.length,'Vocabulary + mistakes'],['Vocabulary due',dueV.length,'Spaced review'],['Recurring mistakes',recurring.length,'Needs targeted practice'],['Recall base',data.vocab.length?Math.round(data.vocab.filter(v=>v.status==='Mastered').length/data.vocab.length*100)+'%':'0%','Mastered / tracked']].map(x=>`<div class="card stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('');document.getElementById('reviewQueue').innerHTML=[...dueV.map(v=>`<div class="row"><div><strong>${esc(v.word)}</strong><small>${esc(v.meaning)} · Review due ${v.review}</small></div><span class="status warn">Vocabulary</span></div>`),...recurring.map(m=>`<div class="row"><div><strong>${esc(m.right)}</strong><small>Recurring mistake · ${m.count}×</small></div><span class="status red">Fix</span></div>`)].join('')||'<div class="empty">Nothing due. Nice. ✨</div>'}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();document.getElementById('monthLabel').textContent=calendarCursor.toLocaleDateString('en-US',{month:'long',year:'numeric'});const first=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate(),prevN=new Date(y,m,0).getDate();let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="cell" style="min-height:auto;background:#f7f9f6;font-weight:750;color:#7a847d">${x}</div>`).join('');for(let i=0;i<first;i++){const d=prevN-first+i+1;html+=`<div class="cell mutedDay"><div class="num">${d}</div></div>`}for(let d=1;d<=n;d++){const k=iso(new Date(y,m,d));const events=[...data.sessions.filter(x=>x.date===k).map(x=>x.activity),...data.speaking.filter(x=>x.date===k).map(x=>'Speaking: '+x.topic),...data.listening.filter(x=>x.date===k).map(x=>'Listening: '+x.title)];html+=`<div class="cell ${k===iso(today)?'today':''}" onclick="selectedDate='${k}';renderCalendar()"><div class="num">${d}</div>${events.slice(0,2).map(e=>`<div class="eventchip">${esc(e)}</div>`).join('')}</div>`}const total=first+n;for(let i=total;i<42;i++){html+=`<div class="cell mutedDay"><div class="num">${i-total+1}</div></div>`}document.getElementById('bigCalendar').innerHTML=html;document.getElementById('selectedDateLabel').textContent=fmt(selectedDate);const items=[...data.sessions.filter(x=>x.date===selectedDate).map(x=>({t:x.activity,s:`${x.duration} min · ${x.skill}`})),...data.speaking.filter(x=>x.date===selectedDate).map(x=>({t:'Speaking: '+x.topic,s:`${x.duration} min · fluency ${x.fluency}/10`})),...data.listening.filter(x=>x.date===selectedDate).map(x=>({t:'Listening: '+x.title,s:`${x.duration} min · ${x.understanding}% understanding`}))];document.getElementById('selectedDayList').innerHTML=items.map(x=>`<div class="row"><div><strong>${esc(x.t)}</strong><small>${esc(x.s)}</small></div><span class="status active">Logged</span></div>`).join('')||'<div class="empty">No learning activity on this date.</div>'}
document.getElementById('prevMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};
function renderAnalytics(){const mins=totalMinutes(),avgSession=data.sessions.length?Math.round(mins/data.sessions.length):0;document.getElementById('analyticsMetrics').innerHTML=[['Total minutes',mins,'All logged sessions'],['Active days',uniqueStudyDays(),'Across saved activity'],['Consistency',daysActiveLast30()+'%','Last 30 days'],['Avg session',avgSession+' min','Across learning log']].map(x=>`<div class="card mini"><h3>${x[0]}</h3><div class="big-number">${x[1]}</div><p>${x[2]}</p></div>`).join('');const heat=document.getElementById('heatmap');heat.innerHTML='';for(let i=27;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=iso(d);const mins=data.sessions.filter(s=>s.date===k).reduce((a,s)=>a+s.duration,0)+data.speaking.filter(s=>s.date===k).reduce((a,s)=>a+s.duration,0)+data.listening.filter(s=>s.date===k).reduce((a,s)=>a+s.duration,0);const level=mins===0?'':mins<15?'l1':mins<30?'l2':mins<60?'l3':'l4';heat.innerHTML+=`<i title="${k}: ${mins} min" style="background:${level==='l1'?'#e8f1d4':level==='l2'?'#d6ebaa':level==='l3'?'#bddd73':level==='l4'?'#c9f34d':'#edf0eb'}"></i>`}const skills=['Speaking','Listening','Vocabulary','Grammar','Pronunciation'];document.getElementById('analyticsWeakness').innerHTML=skills.sort((a,b)=>skillValue(a)-skillValue(b)).map((s,i)=>`<div class="row"><div><strong>${i+1}. ${s}</strong><small>${skillValue(s)}% current estimate</small></div><span class="status ${i===0?'warn':''}">${i===0?'Priority':'Focus'}</span></div>`).join('');const sources={};data.sessions.forEach(s=>sources[s.source]=(sources[s.source]||0)+1);document.getElementById('sourceAnalytics').innerHTML=Object.entries(sources).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>`<div class="card mini"><h3>${esc(x[0])}</h3><div class="big-number">${x[1]}</div><p>Learning log sessions from this source.</p></div>`).join('')}
function renderReflections(){document.getElementById('reflectionList').innerHTML=data.reflections.map(r=>`<div class="row"><div><strong>${r.date}</strong><small><b>Improved:</b> ${esc(r.improved)}<br><b>Difficult:</b> ${esc(r.difficult)}<br><b>Next:</b> ${esc(r.next)}</small></div><span class="status active">Saved</span></div>`).join('')||'<div class="empty">No reflections yet.</div>'}
document.querySelectorAll('.clear-data-btn').forEach(b=>b.addEventListener('click',openClearData));document.getElementById('learningSkillFilter').onchange=renderLearning;document.getElementById('learningSourceFilter').onchange=renderLearning;document.getElementById('clearFilters').onclick=()=>{document.getElementById('learningSkillFilter').value='all';document.getElementById('learningSourceFilter').value='all';renderLearning()};document.getElementById('vocabSearch').oninput=renderVocab;document.getElementById('vocabStatusFilter').onchange=renderVocab;document.getElementById('reviewNow').onclick=()=>showPage('review');
document.getElementById('globalSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;const hits=[...data.vocab.filter(v=>(v.word+' '+v.meaning).toLowerCase().includes(q)).map(()=>['vocab']),...data.resources.filter(r=>(r.title+' '+r.notes).toLowerCase().includes(q)).map(()=>['resources']),...data.sessions.filter(s=>(s.activity+' '+s.notes).toLowerCase().includes(q)).map(()=>['learning'])];if(hits.length===1)showPage(hits[0][0])};
renderAll();

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=5').catch(()=>{}));}
